title: "SITE 1101 · Principles of Information Systems"
description: "ADA University — Fall 2025"
theme: null
markdown: kramdown
plugins: []
url: "https://rahmankarimov.github.io"
baseurl: "/SITE_blog"
include: ["index.html", "style.css", "script.js"]
